//plugins {
//    id 'java'
//}
//
//group = 'org.example'
//version = '1.0-SNAPSHOT'
//
//repositories {
//    mavenCentral()
//}
//
//dependencies {
//    // https://mvnrepository.com/artifact/org.seleniumhq.selenium/selenium-java
//    implementation("org.seleniumhq.selenium:selenium-java:4.31.0")
//    implementation("io.github.bonigarcia:webdrivermanager:5.8.0")
//    // https://mvnrepository.com/artifact/org.testng/testng
//    testImplementation("org.testng:testng:7.10.2")
//    // https://mvnrepository.com/artifact/com.googlecode.json-simple/json-simple
//    implementation("com.googlecode.json-simple:json-simple:1.1.1")
//    // https://mvnrepository.com/artifact/org.apache.commons/commons-csv
//    implementation("org.apache.commons:commons-csv:1.14.0")
//    // https://mvnrepository.com/artifact/io.qameta.allure/allure-testng
//    implementation("io.qameta.allure:allure-testng:2.29.1")
//    // https://mvnrepository.com/artifact/com.github.javafaker/javafaker
//    implementation("com.github.javafaker:javafaker:1.0.2")
//// https://mvnrepository.com/artifact/javax.mail/javax.mail-api
//    implementation("javax.mail:javax.mail-api:1.6.2")
//    implementation ('com.sun.mail:javax.mail:1.6.2')
//    implementation 'com.sun.mail:jakarta.mail:2.0.1'
//}
//
//test {
//    useJUnitPlatform()
//}

plugins {
    id 'java'
}

group = 'org.example'
version = '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

dependencies {
    // Selenium WebDriver
    implementation("org.seleniumhq.selenium:selenium-java:4.31.0")

    // WebDriver Manager for managing browser drivers automatically
    implementation("io.github.bonigarcia:webdrivermanager:5.8.0")

    // TestNG for testing
    testImplementation("org.testng:testng:7.10.2")

    // JSON simple for reading/writing JSON data
    implementation("com.googlecode.json-simple:json-simple:1.1.1")

    // Apache Commons CSV
    implementation("org.apache.commons:commons-csv:1.14.0")

    // Allure TestNG for reporting
    implementation("io.qameta.allure:allure-testng:2.29.1")

    // Java Faker for generating fake data
    implementation("com.github.javafaker:javafaker:1.0.2")

    // JavaMail API for email functionality
    implementation("javax.mail:javax.mail-api:1.6.2")
    implementation('com.sun.mail:javax.mail:1.6.2')
    implementation 'com.sun.mail:jakarta.mail:2.0.1'
}

test {
    useTestNG()  // Make sure you are using TestNG, not JUnit
    testLogging.showStandardStreams = true
}
